DROP TABLE IF EXISTS studyfields CASCADE;

DROP TABLE IF EXISTS orientations CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS user_orientations CASCADE;

DROP TABLE IF EXISTS likes CASCADE;
